server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      #label: master
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/kangrootom/microservicecloud-config.git
          username: kangrootom
          password: cgc111333

